stages:
  - lint
  - test

lint_job:
  stage: lint
  script:
    - pip install flake8
    - flake8 text_analyzer

test_job:
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m unittest discover text_analyzer/tests
